site_name: Stride Framework
site_description: Documentação gerada a partir do código real de core-framework
site_url: https://<your-org>.github.io/core-framework
strict: false
repo_url: https://github.com/SorPuti/core-framework
nav:
  - Home: README.md
  - Introduction: introduction.md
  - Architecture: architecture.md
  - Core Concepts: core-concepts.md
  - Modules:
      - Overview: modules/README.md
  - API:
      - Overview: api/README.md
  - Examples:
      - Overview: examples/README.md
  - Troubleshooting: troubleshooting.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

plugins:
  - search

theme:
  name: readthedocs
